# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "aVbciP06NZxelg7K"

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "gglslhHvmy7Adk3D"
    salt: "kgldSfl86JncXa57uiS2"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  esits.org:
    env:
      db_password: "lf{ksdTy:o8/96#DsasloIurw"
      # Generate your keys here: https://roots.io/salts.html
      auth_key: ".vtc9`/wZ:lYf=?YRVi=xHhQQW%a!knSbHTd#9n]l`Dn6q9,);bPJ<B=}U_MWaX3"
      secure_auth_key: "=F?4#F5$pWir5fkVWPgOxs``<^>v:HU5:f{RZjcdFhgRe$o.SnA)2^VA:..<sZR2"
      logged_in_key: "TzN<{F<3p?OI>Spt0G3NAKop14p(Os5DvSe]J$(uedwt`KDD+a0?@N`7hDW]v0XB"
      nonce_key: ".G_RVF>wpb{SMc*XF:8`1|tb6%3W=#!mrBrX34zX[?hmAQ.CUvZg3B6/0.o!h2jN"
      auth_salt: "J61fbeIqA+CPfx7@&Z+Z<N@4rgN{_Htcz>>H>0%K,&e3+$O6Fi:yP1K1teOt+&Sx"
      secure_auth_salt: "Q/ldnEK/SFkfzW?6qpdpNyYV{$TKvIt+<4[1E_?6db$,:Zs-gU2T,LrXHP/|l$GP"
      logged_in_salt: "7Ea2Xt+U=Kz<1Q{^67V*UvSBJ;Hw1z}VZ:/z2)#N}IS>px2,X+K-rcBu%#n*K:Ab"
      nonce_salt: "[wX37ED7t(3a%]&)|zl3tSw1_MT4]W?pj8wqhN2yp+?M&Fc3&7Z=XdP.7;nn-`-b"
