# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  example.com:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "UV@3yjKFyw:F{sJ_.l7l$<*Z[!Ag:w73|`_j7cK4n^GI$;g(jAH!o<F3dEtz{34p"
      secure_auth_key: "2U3BFf?p(n-oBsq|aVb&GH2pQ;/eh2wY-<@+3|Cxy#)5dOtYMABq*qa&VC}#@>>Q"
      logged_in_key: "k6QHn@@7e#o|T1Mck6vsPy#NS^P_tgYXMD]%JB/|MVeX{%63j.v]m]#:/#!P|.n1"
      nonce_key: "`av<XD*,6CBS:T.H4_TZN:Ev#<hLK;?iMq({|<V?lXY8:ciP06N?XXhIy&/O6S.a"
      auth_salt: "x2$HcQ-L&G#dz*F=*p?lXrSUD0izoE|X8Bn]Hfbgz5b%J)bbcN/D.R%WrLgq@7:+"
      secure_auth_salt: "hJ^(t0ho;e*/R6d)H+!:w!]),AQj8cJ@QgGI:ug{l<X}tl(oWEnC9z!`5!QVH[*Z"
      logged_in_salt: "#0^!<#Zxelg7K.MM_P9rpZEbsFH|$h|err8%(wF)sk!OYwvWaF]0@|rznJXuzm5T"
      nonce_salt: "PbnNbAVq>fw$j<I6f^{=p2,oZlxTzcDpz&Co=@)cS(zd%JF%Ua!1[`7Z>:c-}h,B"